(* ::Package:: *)

(* Complete operator-weighted three-particle photon-DA contributions for the
   Ds/Bs gamma E1 basis currents.

   The formulas use

     a(alpha,v) = alpha_qbar + v alpha_g

   and keep the two virtualities independent until the double Borel transform.
   The ordinary local term -<sbar s>/12 is not part of this transition OPE.
   The channel-specific gluonic three-particle term retains the raw Borel
   factor EQ, as in the Ds1 -> Ds gamma sum rule.  The distinct
   gauge-completion electromagnetic term follows Rohrwild's IF-type
   continuum subtraction and carries EQ-E0.

   A crucial trace correction is incorporated here: the
   x_alpha G^{alpha beta} gamma_beta term of the heavy-quark propagator has no
   (slash k + m_Q) numerator.  Its B-current E1 trace therefore vanishes.

   Run from papers/Ds_Bs_gamma with

     /Applications/Wolfram.app/Contents/MacOS/WolframKernel -noinit \
       -noprompt -script scripts/step15_complete_three_particle_borel.wl
*)

ClearAll[
  a, a0, aq, aqp, aqb, aqbp, beta, ag, v, mQ, ms, M2, EQ, E0,
  eS, eQ, ssCond, S3, St3, T13, T23, T33, T43, Sg3, T4g3,
  lineProjection, pLine, pLinePrime, fGSigma, fGX, fGA,
  fGammaSigma, fGammaA, tA3g, tB3g, tA3em, tB3em, rQ,
  checks, outFile, stream
];

EQ = Exp[-mQ^2/M2];
E0 = Exp[-s0/M2];
rQ = mQ/(mQ + ms);

(* Delta-supported three-particle line projection.  The two domains are the
   explicit solution of alpha_qbar + v alpha_g = z on the physical simplex. *)
lineProjection[fun_, z_] :=
  Inactive[Integrate][
    Inactive[Integrate][
      fun[
        1 - z - (1 - v) ag,
        z - v ag,
        ag,
        v
      ],
      {ag, 0, (1 - z)/(1 - v)}
    ],
    {v, 0, z}
  ] +
  Inactive[Integrate][
    Inactive[Integrate][
      fun[
        1 - z - (1 - v) ag,
        z - v ag,
        ag,
        v
      ],
      {ag, 0, z/v}
    ],
    {v, z, 1}
  ];

(* Support-corrected line density generated by Rohrwild's P functional.
   It is obtained by doing the u-delta integral before the Borel transform.
   In particular, the second term has beta >= z; the zero lower limit printed
   in the original symmetric formula is outside the Borel support and produces
   a spurious logarithmic divergence. *)
pLine[fun_, z_] :=
  Inactive[Integrate][
    Inactive[Integrate][
      Inactive[Integrate][
        (z - aqb)/(1 - aq - aqb)^2
          fun[aq, aqb, 1 - aq - aqb],
        {aqb, 0, z}
      ],
      {aqp, 0, aq}
    ],
    {aq, 0, 1 - z}
  ] -
  Inactive[Integrate][
    Inactive[Integrate][
      z/beta^2 Inactive[Integrate][
        fun[aq, aqbp, 1 - aq - aqbp],
        {aqbp, 0, beta}
      ],
      {beta, z, 1 - aq}
    ],
    {aq, 0, 1 - z}
  ] +
  Inactive[Integrate][
    z/(1 - aq)^2 Inactive[Integrate][
      Inactive[Integrate][
        fun[aqp, aqb, 1 - aqp - aqb],
        {aqb, 0, 1 - aqp}
      ],
      {aqp, 0, aq}
    ],
    {aq, 0, 1 - z}
  ];

pLinePrime[fun_, z_] :=
  Inactive[D][pLine[fun, a], a] /. a -> z;

(* Operator weights.  The first line is the sigma_{alpha beta} propagator
   sector.  The second is the explicit-v x_alpha G gamma_beta sector. *)
fGSigma[aq_, aqb_, ag_, v_] :=
  S3[aq, aqb, ag] + St3[aq, aqb, ag] -
  T13[aq, aqb, ag] - T23[aq, aqb, ag] +
  T33[aq, aqb, ag] + T43[aq, aqb, ag];

fGX[aq_, aqb_, ag_, v_] :=
  2 v (-S3[aq, aqb, ag] - T33[aq, aqb, ag] +
    T23[aq, aqb, ag]);

fGA[aq_, aqb_, ag_, v_] :=
  fGSigma[aq, aqb, ag, v] + fGX[aq, aqb, ag, v];

fGammaSigma[aq_, aqb_, ag_, v_] :=
  Sg3[aq, aqb, ag] - T4g3[aq, aqb, ag];

fGammaA[aq_, aqb_, ag_, v_] :=
  (1 - 2 v) Sg3[aq, aqb, ag] - T4g3[aq, aqb, ag];

(* The P-functional numerator p.q must be Borel transformed rather than
   replaced by a pole-mass difference.  Relative to the symmetric expression
   2 (m_P^2-m_A^2)/M^2 P[T4gamma], the exact n=2 map

     B[(p.q) F/D^2] = -(M^2 EQ/2) F'(a0)

   gives +2 pLinePrime[T4gamma,a0]. *)
tA3g =
  eS ssCond EQ lineProjection[fGA, a0];

tB3g =
  eS ssCond EQ rQ lineProjection[fGSigma, a0];

tA3em =
  eQ ssCond (EQ - E0) (
    lineProjection[fGammaA, a0] +
    2 pLinePrime[T4g3, a0]
  );

tB3em =
  eQ ssCond (EQ - E0) rQ (
    lineProjection[fGammaSigma, a0] +
    2 pLinePrime[T4g3, a0]
  );

checks = FullSimplify /@ {
  fGA[aq, aqb, ag, v] -
    (fGSigma[aq, aqb, ag, v] + fGX[aq, aqb, ag, v]),
  fGammaA[aq, aqb, ag, v] -
    (fGammaSigma[aq, aqb, ag, v] - 2 v Sg3[aq, aqb, ag]),
  tB3g - eS ssCond EQ rQ lineProjection[fGSigma, a0],
  tB3em - eQ ssCond (EQ - E0) rQ (
    lineProjection[fGammaSigma, a0] +
    2 pLinePrime[T4g3, a0])
};

outFile = FileNameJoin[
  {Directory[], "outputs", "step15_complete_three_particle_borel.txt"}];
stream = OpenWrite[outFile];
WriteString[stream,
  "Complete three-particle Borel invariants\n",
  "========================================\n\n"];
WriteString[stream, "F_A^g = ", ToString[fGA[aq, aqb, ag, v], InputForm], "\n\n"];
WriteString[stream, "F_B^g/r_Q = ",
  ToString[fGSigma[aq, aqb, ag, v], InputForm], "\n\n"];
WriteString[stream, "F_A^gamma = ",
  ToString[fGammaA[aq, aqb, ag, v], InputForm], "\n\n"];
WriteString[stream, "F_B^gamma/r_Q = ",
  ToString[fGammaSigma[aq, aqb, ag, v], InputForm], "\n\n"];
WriteString[stream, "T_A^(3p,g) = ", ToString[tA3g, InputForm], "\n\n"];
WriteString[stream, "T_B^(3p,g) = ", ToString[tB3g, InputForm], "\n\n"];
WriteString[stream, "T_A^(3p,em) = ", ToString[tA3em, InputForm], "\n\n"];
WriteString[stream, "T_B^(3p,em) = ", ToString[tB3em, InputForm], "\n\n"];
WriteString[stream, "Assembly residuals (all must vanish):\n",
  ToString[checks, InputForm], "\n"];
Close[stream];

Print["three-particle assembly residuals = ", checks];
Print["Wrote: ", outFile];
Quit[];
