"""Python preview fallback for Figure 2.

The primary publication candidate is the Mathematica/MaTeX output generated by
``plot_figure2.wl``.  This preview uses the same CSV and plot choices.
"""

from __future__ import annotations

import csv
import os
from pathlib import Path


HERE = Path(__file__).resolve().parent
os.environ.setdefault("MPLCONFIGDIR", str(HERE / ".matplotlib"))
os.environ.setdefault("XDG_CACHE_HOME", str(HERE / ".cache"))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator


DATA = HERE / "figure2_mixing_angle_widths.csv"
OUT_PDF = HERE / "figure2_mixing_angle_widths_python.pdf"
OUT_PNG = HERE / "figure2_mixing_angle_widths_python.png"

STYLES = {
    "low": {"color": "#0047ab", "linestyle": "-", "label": "lower state"},
    "high": {"color": "#111111", "linestyle": "--", "label": "higher state"},
}

PANELS = [
    {
        "sector": "Ds",
        "title": r"$D_{s1}\to D_s\gamma$",
        "states": [("Ds1_2460", r"$D_{s1}(2460)$"), ("Ds1_2536", r"$D_{s1}(2536)$")],
        "ylim": (0.0, 52.0),
        "legend_anchor": (0.08, 0.70),
        "theta_label": (34.45, 26.0),
    },
    {
        "sector": "Bs",
        "title": r"$B_{s1}\to B_s\gamma$",
        "states": [("Bs1_5750", r"$B_{s1}(5750)$"), ("Bs1_5830", r"$B_{s1}(5830)$")],
        "ylim": (0.0, 30.0),
        "legend_anchor": (0.08, 0.72),
        "theta_label": (34.45, 15.0),
    },
]


def load_rows() -> list[dict[str, str]]:
    with DATA.open() as handle:
        return list(csv.DictReader(handle))


def curve(rows: list[dict[str, str]], state: str) -> tuple[list[float], list[float], str]:
    selected = [row for row in rows if row["state"] == state]
    selected.sort(key=lambda row: float(row["theta_deg"]))
    combo = selected[0]["combo"]
    return (
        [float(row["theta_deg"]) for row in selected],
        [float(row["Gamma_keV"]) for row in selected],
        combo,
    )


def add_inline_legend(ax, entries, anchor):
    x0, y0 = anchor
    line_len = 0.11
    step = 0.09
    for index, (style, label) in enumerate(entries):
        y = y0 - index * step
        ax.plot(
            [x0, x0 + line_len],
            [y, y],
            transform=ax.transAxes,
            color=style["color"],
            linestyle=style["linestyle"],
            lw=2.0,
            clip_on=False,
        )
        ax.text(
            x0 + line_len + 0.02,
            y,
            label,
            transform=ax.transAxes,
            ha="left",
            va="center",
            fontsize=8.5,
            color="0.10",
        )


def main() -> None:
    rows = load_rows()
    fig, axes = plt.subplots(1, 2, figsize=(7.1, 3.25), constrained_layout=True)
    for ax, panel in zip(axes, PANELS):
        entries = []
        for state, label in panel["states"]:
            xs, ys, combo = curve(rows, state)
            style = STYLES[combo]
            ax.plot(xs, ys, color=style["color"], linestyle=style["linestyle"], lw=2.0)
            entries.append((style, label))
        ax.axvline(35.3, color="0.45", linestyle=":", lw=1.4)
        ax.text(*panel["theta_label"], r"$35.3^\circ$", fontsize=8.5, color="0.30", ha="center", va="center")
        ax.set_title(panel["title"], fontsize=11)
        ax.set_xlim(25.0, 45.0)
        ax.set_ylim(*panel["ylim"])
        ax.set_xlabel(r"$\theta$ [deg]")
        ax.set_ylabel(r"$\Gamma$ [keV]")
        ax.grid(False)
        ax.tick_params(direction="in", top=True, right=True, labelsize=9)
        ax.yaxis.set_major_locator(MaxNLocator(nbins=5))
        add_inline_legend(ax, entries, panel["legend_anchor"])
    fig.savefig(OUT_PDF)
    fig.savefig(OUT_PNG, dpi=240)
    print(f"Wrote {OUT_PDF}")
    print(f"Wrote {OUT_PNG}")


if __name__ == "__main__":
    main()
